zomatoCharocic/zomatoCharocic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('zomato_app.urls'))
]

zomatoCharocic/zomato_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
   path('', views.index, name='index'),
   path('view_menu/', views.view_menu, name='view_menu'),
   path('add_dish/', views.add_dish, name='add_dish'),
   path('add_dish_to_menu/', views.add_dish_to_menu, name='add_dish_to_menu'),
   path('remove_dish/<int:dish_id>/', views.remove_dish, name='remove_dish'),
   path('update_availability/<int:dish_id>/', views.update_availability, name='update_availability'),
   path('add_customer/', views.add_customer, name='add_customer'),
   path('view_customers/', views.view_customer_list, name='view_customers'),
   path('add-order/', views.add_order, name='add_order'),
   path('view-order-history/', views.view_order_history, name='view_order_history'),
   path('view_customer_list/', views.view_customer_list, name='view_customer_list'),
   path('view-customer-order-history/<int:customer_id>/', views.view_customer_order_history, name='view_customer_order_history'),
]

zomatoCharocic/zomato_app/models.py
from django.db import models

class Dish(models.Model):
    dish_id = models.AutoField(primary_key=True)
    dish_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    availability = models.BooleanField(default=True)

    def __str__(self):
        return self.dish_name

class Customer(models.Model):
    customer_name = models.CharField(max_length=100)
    address = models.CharField(max_length=200, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.customer_name

class Menu(models.Model):
    dish = models.OneToOneField(Dish, on_delete=models.CASCADE, primary_key=True)
    description = models.TextField()

    def __str__(self):
        return self.dish.dish_name

class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    status_choices = (
        ('received', 'Received'),
        ('preparing', 'Preparing'),
        ('ready', 'Ready for Pickup'),
        ('delivered', 'Delivered')
    )
    status = models.CharField(max_length=20, choices=status_choices, default='received')
    dishes = models.ManyToManyField(Dish, through='OrderDish')

    def __str__(self):
        return f"Order ID: {self.order_id}, Customer: {self.customer}, Status: {self.status}"

class OrderDish(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_subtotal(self):
        return self.dish.price * self.quantity

zomatoCharocic/zomato_app/forms.py
from django import forms
from .models import Dish, Menu, Customer

class AddDishForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = ['dish_name', 'price', 'availability']

class AddDishToMenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['dish', 'description']


class CustomerCreateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['customer_name', 'address', 'phone_number']

zomatoCharocic/zomato_app/views.py
from django.shortcuts import render, redirect
from .models import Dish, Menu, Customer, OrderDish, Order
from .forms import AddDishForm, AddDishToMenuForm, CustomerCreateForm
# Create your views here.


def index(request):
    return render(request, 'index.html')

def view_menu(request):
    menu_items = Menu.objects.all()
    return render(request, 'view_menu.html', {'menu_items': menu_items})

def add_dish(request):
    if request.method == 'POST':
        form = AddDishForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('view_menu')  # Redirect to the menu page after adding the dish
    else:
        form = AddDishForm()
    return render(request, 'add_dish.html', {'form': form})

def add_dish_to_menu(request):
    if request.method == 'POST':
        form = AddDishToMenuForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('view_menu')  # Redirect to view_menu page after adding the dish
    else:
        form = AddDishToMenuForm()
    return render(request, 'add_dish_to_menu.html', {'form': form})


def remove_dish(request, dish_id):
    try:
        menu_item = Menu.objects.get(dish_id=dish_id)
        menu_item.delete()
        return redirect('view_menu')
    except Menu.DoesNotExist:
        # Handle the case when the menu item with the given dish_id doesn't exist
        return redirect('view_menu')


def update_availability(request, dish_id):
    try:
        dish = Dish.objects.get(pk=dish_id)
        # Toggle the availability status
        dish.availability = not dish.availability
        dish.save()
        return redirect('view_menu')  # Redirect back to the menu page
    except Dish.DoesNotExist:
        # Handle the case when the dish with the given dish_id doesn't exist
        return redirect('view_menu')



def add_customer(request):
    if request.method == 'POST':
        form = CustomerCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('view_customers')
    else:
        form = CustomerCreateForm()

    return render(request, 'add_customer.html', {'form': form})


def view_customer_list(request):
    customers = Customer.objects.all()
    return render(request, 'customer_list.html', {'customers': customers})


def add_order(request):
    customers = Customer.objects.all()
    dishes = Dish.objects.filter(availability=True)

    if request.method == 'POST':
        customer_id = request.POST.get('customer')
        selected_dishes = request.POST.getlist('dishes')

        customer = Customer.objects.get(id=customer_id)
        order = Order.objects.create(customer=customer)

        for dish_id in selected_dishes:
            dish = Dish.objects.get(id=dish_id)
            order_dish = OrderDish.objects.create(order=order, dish=dish)

        return redirect('view_order_history')  # Redirect to view order history page

    return render(request, 'add_order.html', {'customers': customers, 'dishes': dishes})


def view_order_history(request):
    orders = Order.objects.all()
    return render(request, 'order_history.html', {'orders': orders})

def view_customer_order_history(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    orders = Order.objects.filter(customer=customer)
    return render(request, 'customer_order_history.html', {'customer': customer, 'orders': orders})

zomatoCharocic/zomato_app/templates/add_customer.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Add Customer</title>
</head>
<body>
  <div class="container">
    <h1>Add Customer</h1>
    <hr>
    <form action="{% url 'add_customer' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="customer_name" class="form-label">Customer Name</label>
        <input type="text" class="form-control" id="customer_name" name="customer_name" required>
      </div>
      <div class="mb-3">
        <label for="address" class="form-label">Address</label>
        <input type="text" class="form-control" id="address" name="address" required>
      </div>
      <div class="mb-3">
        <label for="phone_number" class="form-label">Phone Number</label>
        <input type="text" class="form-control" id="phone_number" name="phone_number" required>
      </div>
      <button type="submit" class="btn btn-primary">Add Customer</button>
    </form>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/add_dish.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
  <title>Office Employee Management System</title>
</head>
<body>
  <div class="container">
    <h1>Add dish</h1>
    <hr>
<!--    <form action="/add_dish" method="post">-->
<!--      {% csrf_token %}-->
<!--      <div class="mb-3">-->
<!--        <label for="dish_name" class="form-label">Dish Name</label>-->
<!--        <input type="text" class="form-control" id="dish_name" name="dish_name" required>-->
<!--      </div>-->
<!--      <div class="mb-3">-->
<!--        <label for="price" class="form-label">price</label>-->
<!--        <input type="number" class="form-control" id="price" name="price" required>-->
<!--      </div>-->
<!--      <button type="submit" class="btn btn-primary">Submit</button>-->
<!--    </form>-->
    <form action="{% url 'add_dish' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="dish_name" class="form-label">Dish Name</label>
        <input type="text" class="form-control" id="dish_name" name="dish_name" required>
      </div>
      <div class="mb-3">
        <label for="price" class="form-label">Price</label>
        <input type="number" class="form-control" id="price" name="price" step="0.01" required>
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="availability" name="availability">
        <label class="form-check-label" for="availability">Availability</label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/add_dish_to_menu.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Zomato Chronicles - Add Dish to Menu</title>
  <!-- Link to Bootstrap CSS -->
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <h2>Add Dish to Menu</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Add Dish</button>
    </form>
  </div>
  <!-- Link to Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/add_order.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Add Order</title>
  <!-- Link to Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <h2>Add Order</h2>
    <form action="{% url 'add_order' %}" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="customer" class="form-label">Select Customer</label>
        <select class="form-control" id="customer" name="customer" required>
          {% for customer in customers %}
            <option value="{{ customer.id }}">{{ customer.customer_name }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label for="dishes" class="form-label">Select Dishes</label>
        <select multiple class="form-control" id="dishes" name="dishes[]" required>
          {% for dish in dishes %}
            <option value="{{ dish.id }}">{{ dish.dish_name }} - ${{ dish.price }}</option>
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Add Order</button>
    </form>
  </div>
  <!-- Link to Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/customer_list.html
<!doctype html>
<html lang="en">
<head>
  <!-- Your head content here -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h2>Customer List</h2>
    <div class="table-responsive">
      <table class="table table-success table-striped-columns">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Customer Name</th>
            <th scope="col">Address</th>
            <th scope="col">Phone Number</th>
          </tr>
        </thead>
        <tbody>
          {% for customer in customers %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ customer.customer_name }}</td>
            <td>{{ customer.address }}</td>
            <td>{{ customer.phone_number }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- Link to Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/customer_order_history.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Customer Order History</title>
  <!-- Link to Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <h2>{{ customer.customer_name }}'s Order History</h2>
    <table class="table table-success table-striped-columns">
      <thead>
        <tr>
          <th>#</th>
          <th>Order ID</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ order.order_id }}</td>
          <td>{{ order.status }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- Link to Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/index.html
<!doctype html>
<html lang="en"> <!-- Set the language to 'en' for English -->
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>Zomato Chronicles</title>
</head>
<body>


  <div class="container">
   <h1>Zomato Chronicles!</h1>

      <hr>
      <a class="btn btn-primary" href="/add_dish" role="button">Add dish</a>
      <a class="btn btn-primary" href="/add_dish_to_menu" role="button">Add dish To Menu</a>
      <a class="btn btn-primary" href="/view_customers" role="button">View All Customers</a>

      <hr>
      <a class="btn btn-primary" href="/add_customer" role="button">Register Customer</a>
      <a class="btn btn-primary" href="/view_menu" role="button">View Menu</a>
      <a class="btn btn-primary" href="/add-order" role="button">Order Food</a>


</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/order_history.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Order History</title>
  <!-- Link to Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <h2>Order History</h2>
    <table class="table table-success table-striped-columns">
      <thead>
        <tr>
          <th>#</th>
          <th>Order ID</th>
<!--           <th>Dish Name</th>-->
          <th>Customer Name</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ order.order_id }}</td>
<!--          <td>-->
<!--            {% for order_dish in order.orderdish_set.all %}-->
<!--              {{ order_dish.dish.dish_name }}<br>-->
<!--            {% endfor %}-->
<!--          </td>-->
          <td>{{ order.customer.customer_name }}</td>
          <td>{{ order.status }}</td>
          <td>
            <a href="{% url 'view_customer_order_history' order.customer.id %}" class="btn btn-primary btn-sm">View Customer Orders</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- Link to Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

zomatoCharocic/zomato_app/templates/view_menu.html
<!doctype html>
<html lang="en">
<head>
  <!-- Your head content here -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-PRrgQVJ8NNHGieOA1grGdCTIt4h21CzJs6SnWH4YMQ6G5F5+IEzOHz67L4SQaF0o" crossorigin="anonymous">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h2>Menu</h2>
    <div class="table-responsive">
      <table class="table table-success table-striped-columns">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Dish Name</th>
            <th scope="col">Dish Price</th>
            <th scope="col">Description</th>
            <th scope="col">Availability</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for menu_item in menu_items %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ menu_item.dish.dish_name }}</td>
            <td>${{ menu_item.dish.price }}</td>
            <td>{{ menu_item.description }}</td>
            <td>
              <form method="post" action="{% url 'update_availability' menu_item.dish.dish_id %}">
                {% csrf_token %}
                {% if menu_item.dish.availability %}
                  <button type="submit" class="btn btn-success btn-sm">Available</button>
                {% else %}
                  <button type="submit" class="btn btn-danger btn-sm">Unavailable</button>
                {% endif %}
              </form>
            </td>
            <td>
              <a href="{% url 'remove_dish' menu_item.dish.dish_id %}" class="btn btn-danger btn-sm">Remove</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <!-- Link to Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>